### PR TITLE
Update some spellings in README

### PR DESCRIPTION
**Pull request by philipturner**
I thought of a few minor changes to words that might enhance the README. Just wanted to let you know!

### CODE REVIEW

**Comment by philipturner** [comment]
It seems like I should update some internal web page documents, as directly editing the README may not change the website.

**Comment by philipturner** [comment]
You may want to choose to squash and merge, if this pull request is accepted.

**Comment by artyom-beilis** [comment]
Thanks for proof-reading. I really need to take care of reading what I write better and using some spellchecker :-)

**Comment by philipturner** [comment]
@artyom-beilis the free version of Grammarly is really amazing for this!

**Pull request merged**
