### PR TITLE
Apple initial support

### PR DESCRIPTION
**Pull request by philipturner**
There is still a long way to go until Apple GPU is truly supported. For example, we may want to manually include the OpenCL 1.2 C++ header with DLPrimitives. Right now, you have to modify a framework in the Xcode macOS SDK, which is less than ideal.

In the future, we should disable HDF5 by default to make it compatible with macOS. You mentioned that it was a future goal anyway.

We should also add that the M1 Max was tested on your README and some benchmarking docs. But we should wait until other compatibility issues are figured out. Also, I could run my Mac mini's Intel UHD 630 on macOS, Linux, and Windows.

Could you compile this on your personal computer and make sure it runs?

### CODE REVIEW

**Comment by artyom-beilis** [comment]
Looks good. Have you managed to run unit tests?

**Comment by philipturner** [comment]
`make test` started segfaulting at the same place it did previously:
```
      Start  1: test_test_case_abs
 1/33 Test  #1: test_test_case_abs ...............   Passed    0.36 sec
      Start  2: test_test_case_activation
 2/33 Test  #2: test_test_case_activation ........   Passed    1.25 sec
      Start  3: test_test_case_batchnorm
 3/33 Test  #3: test_test_case_batchnorm .........   Passed    4.70 sec
      Start  4: test_test_case_concat
 4/33 Test  #4: test_test_case_concat ............   Passed    0.08 sec
      Start  5: test_test_case_conv2d
 5/33 Test  #5: test_test_case_conv2d ............***Exception: SegFault 50.92 sec
      Start  6: test_test_case_conv2d_dsc
```

The following commands pass:
```
./test_util 0:0
./test_random 0:0 // segfaults if I don't pass in "0:0"
./test_context 0:0
--> Basic context
    Apple M1 Max on Apple
    Ok
./dlprim_flops 0:0
```

The following commands fail:
[test_failures.txt](https://github.com/artyom-beilis/dlprimitives/files/8113679/test_failures.txt)

**Comment by artyom-beilis** [comment]
Ok first of all please run full tests even if some segfault - and send me `Testing/Temporary/LastTest.log` and `LastTestsFailed.log`  under build directory

Another please run the test under debugger and give me a stack trace:

```
gdb /test_from_template
r 0:0 ../tests/test_case_conv2d.json

And when it crashes, give output of `bt` - backtrace - see where exactly the failure occurs

**Comment by philipturner** [comment]
Here are the test and crash logs:

[dlprimitives_test_logs.zip](https://github.com/artyom-beilis/dlprimitives/files/8116389/dlprimitives_test_logs.zip)

**Comment by artyom-beilis** [comment]
Ok, the good news is that it does not fails in GPU but rather in CPU so it would be way easier to debug.

What is the compiler are you using and what version? I want to reproduce it at my machine.

**Comment by philipturner** [comment]
Apple Clang compiler, using LLDB as the debugger. It runs on Windows and I've seen an option to download it in Visual Studio. If you can't reproduce it on Windows, we can both try it on Docker.

**Comment by artyom-beilis** [comment]
clang 10 works ok. I just tested on Linux. Also test_json failure is even more puzzling. 

Maybe it is somehow arm related. Are you building 32 or 64 bit version?

**Comment by philipturner** [comment]
That's a 64-bit architecture. I don't see a reason why macOS would make 32-bit code. Unlike Windows, it doesn't support backward compatibility for that.

**Comment by philipturner** [comment]
I can run this on my Intel mac mini, or on an x86_64 emulated Docker VM, to see if this is architecture-dependent.

**Comment by artyom-beilis** [comment]
> Did you reproduce the failure?

I managed. It was creating a reference to invalid location witch lead to undefined behavior. Clang does it differently from GCC. I cought it with clang-10 and valgrind that reported invalid access (also program didn't crashed on Linux/x64)

Take latest update with fix.

Thanks for the report and backtrace it allowed me to pinpoint the issue!

**Comment by artyom-beilis** [comment]
Also please run unit-tests to see if there any more failures

**Comment by philipturner** [comment]
The convolutions took extremely long. About how long do they take on your GPUs?
```
(base) philipturner@philipsm1maxmbp build % make test
Running tests...
Test project /Users/philipturner/Documents/building-dlprimitives/dlprimitives/build
      Start  1: test_test_case_abs
 1/33 Test  #1: test_test_case_abs ...............   Passed    0.62 sec
      Start  2: test_test_case_activation
 2/33 Test  #2: test_test_case_activation ........   Passed    1.16 sec
      Start  3: test_test_case_batchnorm
 3/33 Test  #3: test_test_case_batchnorm .........   Passed    4.48 sec
      Start  4: test_test_case_concat
 4/33 Test  #4: test_test_case_concat ............   Passed    0.06 sec
      Start  5: test_test_case_conv2d
 5/33 Test  #5: test_test_case_conv2d ............   Passed  511.23 sec
      Start  6: test_test_case_conv2d_dsc
 6/33 Test  #6: test_test_case_conv2d_dsc ........   Passed  438.03 sec
      Start  7: test_test_case_conv2d_gemm
 7/33 Test  #7: test_test_case_conv2d_gemm .......   Passed  442.57 sec
      Start  8: test_test_case_conv2d_win
 8/33 Test  #8: test_test_case_conv2d_win ........   Passed  436.03 sec
      Start  9: test_test_case_elementwise
 9/33 Test  #9: test_test_case_elementwise .......   Passed    1.99 sec
      Start 10: test_test_case_global_pooling
10/33 Test #10: test_test_case_global_pooling ....   Passed    4.28 sec
      Start 11: test_test_case_hardtanh
11/33 Test #11: test_test_case_hardtanh ..........   Passed    0.54 sec
      Start 12: test_test_case_inner_product
12/33 Test #12: test_test_case_inner_product .....   Passed   96.18 sec
      Start 13: test_test_case_log_softmax
13/33 Test #13: test_test_case_log_softmax .......   Passed    0.29 sec
      Start 14: test_test_case_mse_loss
14/33 Test #14: test_test_case_mse_loss ..........   Passed    0.12 sec
      Start 15: test_test_case_nll_loss
15/33 Test #15: test_test_case_nll_loss ..........   Passed    0.26 sec
      Start 16: test_test_case_param
16/33 Test #16: test_test_case_param .............   Passed    0.07 sec
      Start 17: test_test_case_pooling2d
17/33 Test #17: test_test_case_pooling2d .........   Passed   69.88 sec
      Start 18: test_test_case_reduction
18/33 Test #18: test_test_case_reduction .........   Passed   20.43 sec
      Start 19: test_test_case_slice
19/33 Test #19: test_test_case_slice .............   Passed    0.05 sec
      Start 20: test_test_case_softmax
20/33 Test #20: test_test_case_softmax ...........   Passed    0.29 sec
      Start 21: test_test_case_softmax_loss
21/33 Test #21: test_test_case_softmax_loss ......   Passed    0.22 sec
      Start 22: test_test_case_threshold
22/33 Test #22: test_test_case_threshold .........   Passed    0.45 sec
      Start 23: test_test_case_tr_conv2d
23/33 Test #23: test_test_case_tr_conv2d .........   Passed   18.66 sec
      Start 24: test_test_case_tr_conv2d_dsc
24/33 Test #24: test_test_case_tr_conv2d_dsc .....   Passed    7.23 sec
      Start 25: test_test_case_tr_conv2d_gemm
25/33 Test #25: test_test_case_tr_conv2d_gemm ....   Passed    7.66 sec
      Start 26: test_test_case_tr_conv2d_win
26/33 Test #26: test_test_case_tr_conv2d_win .....   Passed    7.30 sec
      Start 27: test_net
27/33 Test #27: test_net .........................   Passed    0.89 sec
      Start 28: test_net_nonopt
28/33 Test #28: test_net_nonopt ..................   Passed    0.10 sec
      Start 29: test_json
29/33 Test #29: test_json ........................***Failed    0.07 sec
      Start 30: test_random
30/33 Test #30: test_random ......................   Passed    0.17 sec
      Start 31: test_context
31/33 Test #31: test_context .....................   Passed    0.14 sec
      Start 32: test_util
32/33 Test #32: test_util ........................   Passed    0.32 sec
      Start 33: test_broadcast_reduce
33/33 Test #33: test_broadcast_reduce ............   Passed    2.35 sec

97% tests passed, 1 tests failed out of 33

Total Test time (real) = 2074.14 sec

The following tests FAILED:
	 29 - test_json (Failed)
Errors while running CTest
Output from these tests are in: /Users/philipturner/Documents/building-dlprimitives/dlprimitives/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
make: *** [test] Error 8
```

**Comment by tangjinchuan** [comment]
Tried Apple Clang from SDK 13.5 to 15, there was no luck do to incompatible issues with a *_v related standard issue (no luck on search engine). But by using Clang from homebrew as well as others package such as opencl -hpp package, it is all about cmakefile settings (no need to modify any project code or SDK) and I got this lib. I have't test it yet.
[libpt_ocl.dylib.zip](https://github.com/user-attachments/files/15928473/libpt_ocl.dylib.zip)

**Pull request merged**
